### ISSUE TITLE
我用ZUK 小米6 红米手机测试了下，发现onPictureTaken 不回调

### ISSUE THREAD

**Issue by Kotlin2022** [smartown/CertificateCamera#1]
camera.takePicture(null, null, pictureCallback); 
 pictureCallback 这个系统方法中onPictureTaken 回调不执行

**Comment by Kotlin2022** [comment]
public void takePhoto(Camera.PictureCallback pictureCallback) {
        if (camera != null) {
            camera.takePicture(null, null, pictureCallback);
            camera.stopPreview();//这里出错了
        }
    }
把camera.stopPreview();这句放到回调完成后执行

**Comment by Smkai** [comment]
坑人啊！  改过来吧 ！ 调试了很久

**Comment by Gloria-Tang-1969** [comment]
还是不行，有改好的吗？

**Comment by Smkai** [comment]
把camera.stopPreview();这句放到回调完成后执行 这个就可以啊！

**Comment by Smkai** [comment]
可以加我好友QQ 35600565

**Comment by spynokia** [comment]
}).start();
                cameraPreview.stopPreview();    
放子线程执行完的后面
